### ISSUE TITLE
Requesting permission to take over the rsvg crate 

### ISSUE THREAD

**Issue by federicomenaquintero** [selaux/rsvg-rs#15]
Hi, @selaux!  Long time no talk :)

In librsvg we've been doing a lot of work to make it possible to finally publish the public Rust API as a crate in crates.io.  This would remove the need for the rsvg-rs binding, as there is a native API now for librsvg.

We had talked about me taking over the rsvg crate in crates.io - is this something you would still agree to doing?  :)

You can see the current discussion in https://gitlab.gnome.org/GNOME/librsvg/-/issues/995

Thanks!

**Comment by selaux** [comment]
Sorry for the late response, I missed that message. Yes I'm still open to hand over the crate.
