### ISSUE TITLE
gtk-rs v0.3.0

### ISSUE THREAD

**Issue by niklasf** [selaux/rsvg-rs#6]
Hi, there's a new release for many of the gtk-rs packages. It would be awesome if rsvg-rs were usable with them.

[Last time](https://github.com/selaux/rsvg-rs/pull/3) I patched files that were automatically generated anyway, so I'll leave it for now. But let me know if you want help with anything.

**Comment by selaux** [comment]
Will have a look...

**Comment by selaux** [comment]
Cann you test wether https://github.com/selaux/rsvg-rs/pull/7 works for you?

**Comment by niklasf** [comment]
Thank you! I just tried to upgrade [chessground](https://github.com/niklasf/rust-chessground) (which uses rsvg to draw the pieces) and it works nicely.

**Comment by selaux** [comment]
Allright, will release new version asap...

**Comment by selaux** [comment]
`0.3.0` released. Please reopen when you find some issues...
